name: build windows unity plugin

inputs:
  backend:
    description: 'js backend'     
    required: true
  config:
    type: choice
    description: Release Or Debug
    default: 'Release'
    options:
    - Release
    - Debug
  arch:
    type: choice
    description: building arch
    default: 'auto'
    options:
      - auto
      - x64
      - ia32
  websocket:
    description: enable websocket
    default: '0'
  build_proj_dir:
    description: 'build project dir'     
    required: false
    default: 'native_src'
  GITHUB_TOKEN:
    required:

runs:
  using: "composite"
  steps:
    - name: Install NASM
      shell: powershell
      run: |
        $url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip"
        $output = "$env:TEMP\nasm.zip"
        $dest = "C:\nasm"
        
        Invoke-WebRequest -Uri $url -OutFile $output -UseBasicParsing
        Expand-Archive -Path $output -DestinationPath $dest -Force
        Remove-Item $output
        
        # 验证安装
        & "$dest\nasm-2.16.01\nasm.exe" -v
        
    - name: Build
      shell: powershell
      run: |
        $env:Path = "C:\nasm\nasm-2.16.01;" + $env:Path
        & "C:\nasm\nasm-2.16.01\nasm.exe" -v
        cd unity
        npm i
        cd ${{ inputs.build_proj_dir }}
        node ../cli make --platform win --backend ${{ inputs.backend }} --config ${{ inputs.config }} --arch ${{ inputs.arch }} --websocket ${{ inputs.websocket }}
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ./unity/Assets/core/upm/Plugins/**/*
        name: Unity_Plugins_${{ inputs.backend }}_${{ inputs.config }}_window
    - name: Clean
      shell: bash
      run: rm -rf ./unity/Assets/core/upm/Plugins/**/*