name: Build CentOS-Compatible QuickJS Backend and PuerTS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/unity_build_centos_quickjs.yml'

jobs:
  build-centos-quickjs:
    name: Build QuickJS Backend and PuerTS for CentOS
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout puerts repository
        uses: actions/checkout@v4
      
      - name: Build CentOS-Compatible QuickJS Backend and PuerTS
        uses: ./.github/workflows/composites/unity-build-centos-quickjs/
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
